link: *.o
	g++ *.o
1: main.cpp
	g++ main.cpp -c
2: huffman.cppm
	g++ huffman.cpp -c
3: cesar.cpp
	g++ cesar.cpp -c
4: test.cpp
	g++ test.cpp -c
5: hash.cpp
	g++ hash.cpp -c
6: program_flow.cpp
	g++ program_flow.cpp -c
7: header.h
	g++ *.cpp -c
8: test.h
	g++ main.cpp test.cpp -c
all:
	g++ *.cpp
debug:
	g++ *.cpp -g
clean:
	rm *.o